name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
      TF_CPP_MIN_LOG_LEVEL: 3
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip uninstall -y tensorflow-macos || true
          pip install tensorflow
      - name: Run tests
        run: |
          pip install pytest
          PYTHONPATH=src pytest tests
